[package]
name="user_land"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
kernel_api_types = {path = "../kernel_api_types"}
owo-colors = "4.2.3"
embedded-graphics = "0.8.1"
heapless = "0.9.2"

[[bin]]
name = "user_land"
test = false
bench = false