[unstable]
# enable the unstable artifact-dependencies feature, see
# https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#artifact-dependencies
bindeps = true

[target.x86_64-unknown-none]
rustflags = ["-C", "relocation-model=static", "-C", "no-redzone"]

[alias]
ktest            = "run -p runner --features kernel_test --"
ktest-mem        = "run -p runner --features test_mem --"
ktest-time       = "run -p runner --features test_time --"
ktest-interrupts = "run -p runner --features test_interrupts --"
ktest-graphics   = "run -p runner --features test_graphics --"
ktest-usermode   = "run -p runner --features test_usermode --"
ktest-keyboard   = "run -p runner --features test_keyboard --"
ktest-ipc        = "run -p runner --features test_ipc --"
ktest-display    = "run -p runner --features test_display --"
ktest-scheduler  = "run -p runner --features test_scheduler --"
ktest-elf        = "run -p runner --features test_elf --"
ktest-sched         = "run -p runner --features test_sched --"
ktest-sched-noelf   = "run -p runner --features test_sched_noelf --"
utest               = "run -p runner --features userspace_test --"
